version: '3.7'

networks:
  nerdsletter-network:

# docker-compose.yml
# Add this top-level entry
services:
  db:
    image: mongo
    container_name: mongodb
    networks:
      - nerdsletter-network
    
  public:
    image: nerdsletter-public:1.0.0 #  from docker hub: yosamac/nerdsletter-public
    container_name: public
    # build: 
    #   context: ./nerdsletter-public
    #   dockerfile: ./public/Dockerfile
    ports:
      - '80:3000'
    networks:
      - nerdsletter-network
    environment: 
      - SUBSCRIPTION_MESH_HOST=subscription
      - SUBSCRIPTION_MESH_PORT=4001
    links: 
      - subscription

  subscription:
    image:  nerdsletter-subscription:1.0.0 # from docker hub: yosamac/nerdsletter-subscription
    container_name: subscription
    # build: 
    #   context: ./subscription
    #   dockerfile: ./nerdsletter-subscription/Dockerfile
    networks:
      - nerdsletter-network
    environment:
      - MONGODB_URI=mongodb://db:27017/nerdsletter_subscription
      - LOG_LEVEL=DEBUG
      - EMAIL_MESH_HOST=email
      - EMAIL_MESH_PORT=4002
    depends_on:
      - db
    links:
      - email
  
  email:
    image: nerdsletter-email:1.0.0  # from docker hub: yosamac/nerdsletter-email
    container_name: email
    # build: 
    #   context: ./email
    #   dockerfile: ./nerdsletter-email/Dockerfile
    networks:
      - nerdsletter-network